name: Docker-hub auto-deploy on merge

on:
  push:
    branches:
      - deploy-testing

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Prepare release
        run: mvn release:prepare -B

      - name: Perform release
        run: mvn release:perform -B

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker-compose build
          docker-compose push

      - name: Clean up
        run: docker-compose down
